
package com.raven.form;

import com.raven.component.Header;
import com.raven.main.Main;
import com.raven.model.StatusType;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;


public class teacher extends javax.swing.JPanel {



   
      public void showrecord() {
   
    dbclass dbclass=new dbclass();
        ResultSet rs = dbclass.getteachers();
        
        try{
            while(rs.next()) {
    String data[]={rs.getString("tname"),rs.getString("tid"),rs.getString("tphone"),rs.getString("t_load"),rs.getString("t_type")};
       
        DefaultTableModel tbmodel=(DefaultTableModel)jTable1.getModel();
        
        tbmodel.addRow(data);
        }}catch(Exception e){
    System.out.println(e);
    }
        
        
     }
 
      
      
      
      

    public teacher() {
        initComponents();
         showrecord();
         AutoCompleteDecorator.decorate(ttype);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        rname = new javax.swing.JLabel();
        rid = new javax.swing.JLabel();
        rload = new javax.swing.JLabel();
        rphone = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        tload = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        ttype = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        search = new com.raven.swing.SearchText();
        rsearch = new javax.swing.JLabel();

        setBackground(new java.awt.Color(242, 242, 242));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel4.setText("ADD TEACHER");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 13, 191, 48));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("FULL NAME");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 76, 110, 26));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("PHONE");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 74, 26));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Total Load");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 192, 140, 26));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("TEACHER ID");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 133, -1, 26));

        name.setForeground(new java.awt.Color(153, 153, 153));
        name.setText("Enter Teacher Name");
        name.setBorder(null);
        name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameFocusLost(evt);
            }
        });
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameKeyReleased(evt);
            }
        });
        jPanel3.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 75, 262, 35));

        id.setForeground(new java.awt.Color(153, 153, 153));
        id.setText("Enter Teacher ID");
        id.setBorder(null);
        id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                idFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                idFocusLost(evt);
            }
        });
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idKeyReleased(evt);
            }
        });
        jPanel3.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 133, 262, 35));

        phone.setForeground(new java.awt.Color(153, 153, 153));
        phone.setText("Enter Teacher Number");
        phone.setBorder(null);
        phone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phoneFocusLost(evt);
            }
        });
        phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                phoneKeyReleased(evt);
            }
        });
        jPanel3.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 259, 35));

        rname.setForeground(new java.awt.Color(255, 0, 0));
        jPanel3.add(rname, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 101, 76, 9));

        rid.setForeground(new java.awt.Color(255, 0, 0));
        jPanel3.add(rid, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 155, 88, 13));

        rload.setForeground(new java.awt.Color(255, 0, 0));
        jPanel3.add(rload, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 212, 53, 11));

        rphone.setForeground(new java.awt.Color(255, 0, 0));
        jPanel3.add(rphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 71, 10));

        jSeparator1.setMinimumSize(new java.awt.Dimension(50, 7));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 110, 262, 10));

        jSeparator2.setMinimumSize(new java.awt.Dimension(50, 7));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 168, 262, 10));

        jSeparator3.setMinimumSize(new java.awt.Dimension(50, 7));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 259, 10));

        tload.setForeground(new java.awt.Color(153, 153, 153));
        tload.setText("Enter Teacher Load");
        tload.setBorder(null);
        tload.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tloadFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tloadFocusLost(evt);
            }
        });
        tload.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tloadKeyReleased(evt);
            }
        });
        jPanel3.add(tload, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 192, 262, 29));

        jSeparator5.setMinimumSize(new java.awt.Dimension(50, 7));
        jPanel3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 221, 259, 10));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Teacher Type");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 140, 26));

        ttype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Internal", "External" }));
        jPanel3.add(ttype, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 160, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jButton2.setBackground(new java.awt.Color(34, 40, 243));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("ADD ");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 102, 51));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("RESET");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(153, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("DELETE ");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SEARCH");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 102, 204));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("SHOW ALL");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 153, 102));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("UPDATE");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 51, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "ID", "PHONE", "Total Load", "Teacher Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/search.png"))); // NOI18N

        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
            .addComponent(search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        rsearch.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 863, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(13, 13, 13)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 230, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(rsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(name.getText().equals("Enter Teacher Name") || name.getText().equals("") || id.getText().equals("Enter Teacher ID") || id.getText().equals("") || tload.getText().equals("Enter Teacher Load") || tload.getText().equals("") || phone.getText().equals("Enter Teacher Number") || phone.getText().equals("") )

        {
            if(name.getText().equals("Enter Teacher Name") || name.getText().equals("")){
                rname.setText("*required");
            }
            else{
                rname.setText("");
            }

            if(id.getText().equals("Enter Teacher ID") || id.getText().equals("")){
                rid.setText("*required");
            }
            else{
                rid.setText("");
            }
            if(tload.getText().equals("Enter Teacher Load") || tload.getText().equals("")){
                rload.setText("*required");
            }
            else{
                rload.setText("");
            }

            if(phone.getText().equals("Enter Teacher Number") || phone.getText().equals("")){
                rphone.setText("*required");
            }
            else{
                rphone.setText("");
            }

        }
        else{
                try {
             dbclass insert=new  dbclass();
             
             ResultSet rs1= insert.checkteacherName(name.getText());
             boolean chkTeacherName=rs1.isBeforeFirst();
             ResultSet rs2 = insert.sreachteacher(id.getText());
             boolean chkTeacherId=rs2.isBeforeFirst();
             ResultSet rs3 = insert.checkteacherNum(phone.getText());
             boolean chkTeacherNum=rs3.isBeforeFirst();
            
            if(chkTeacherName==true || chkTeacherId==true || chkTeacherNum==true){
            
                if(chkTeacherName==true)
                {
                JOptionPane.showMessageDialog(null,"dulicate entry This Name " +name.getText()+ " is Name of  Another Teacher Do little bit Changing in Name","dulicate entry",JOptionPane.WARNING_MESSAGE);
                }
                else if(chkTeacherId==true)
                {
                JOptionPane.showMessageDialog(null,"dulicate entry "+id.getText()+ " is Already Found in Database ","dulicate entry",JOptionPane.WARNING_MESSAGE);
                }
                else if(chkTeacherNum==true)
                {
                JOptionPane.showMessageDialog(null,"dulicate entry This Mobile Num "+phone.getText()+ " is Already in  use of Another Teacher ","dulicate entry",JOptionPane.WARNING_MESSAGE);
                }
            }
          else{
            
            insert.insertteacher(name.getText(),id.getText(),phone.getText(),tload.getText(),ttype.getSelectedItem().toString());
            JOptionPane.showMessageDialog(null,"teacher succesfully added","teacher add",JOptionPane.INFORMATION_MESSAGE);
            DefaultTableModel tbmodel=(DefaultTableModel)jTable1.getModel();
            tbmodel.setRowCount(0);
            showrecord();

            name.setText("Enter Teacher Name");
            name.setForeground(new Color(153,153,153));
            rname.setText("");
            id.setText("Enter Teacher ID");
            id.setForeground(new Color(153,153,153));
            rid.setText("");
            rload.setText("");
            phone.setText("Enter Teacher Number");
            phone.setForeground(new Color(153,153,153));
            rphone.setText("");
            tload.setText("Enter Teacher Load");
            tload.setForeground(new Color(153,153,153));
            rload.setText("");
          }

        
            }
            catch (SQLException ex) {
                System.out.println(ex);   
                 }
    }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        name.setText("Enter Teacher Name");
        name.setForeground(new Color(153,153,153));
        rname.setText("");
        id.setText("Enter Teacher ID");
        id.setForeground(new Color(153,153,153));
        rid.setText("");
        rload.setText("");
        phone.setText("Enter Teacher Number");
        phone.setForeground(new Color(153,153,153));
        rphone.setText("");
        tload.setText("Enter Teacher Load");
        tload.setForeground(new Color(153,153,153));
        rload.setText("");
        tload.setText("Enter Teacher Load");
        tload.setForeground(new Color(153,153,153));
        rload.setText("");
        search.setText(null);
        rsearch.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dbclass dbclass=new dbclass();
        ResultSet rs = dbclass.sreachteacher(search.getText());

        if(search.getText().equals("Search here ...") || search.getText().equals("")){
            rsearch.setText("*required");
        }
        else{
            rsearch.setText("");
            try {
                if(rs.isBeforeFirst()==true){

                    dbclass.deleteteacher(search.getText());
                    JOptionPane.showMessageDialog(null,"teacher succesfully deleted","teacher delete",JOptionPane.INFORMATION_MESSAGE);
                    DefaultTableModel tbmodel=(DefaultTableModel)jTable1.getModel();
                    tbmodel.setRowCount(0);
                    showrecord();
                    name.setText("Enter Teacher Name");
                    name.setForeground(new Color(153,153,153));
                    rname.setText("");
                    id.setText("Enter Teacher ID");
                    id.setForeground(new Color(153,153,153));
                    rid.setText("");
                    rload.setText("");
                    phone.setText("Enter Teacher Number");
                    phone.setForeground(new Color(153,153,153));
                    rphone.setText("");
                    tload.setText("Enter Teacher Load");
                    tload.setForeground(new Color(153,153,153));
                    rload.setText("");
                    search.setText(null);

                }  else{
                    JOptionPane.showMessageDialog(null,"record not found","record not found",JOptionPane.ERROR_MESSAGE);
                }   } catch (SQLException ex) {
                    System.out.println(ex);
                }

            }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dbclass dbclass=new dbclass();
        ResultSet rs = dbclass.sreachteacher(search.getText());
        if(search.getText().equals("Search here ...") || search.getText().equals("")){
            rsearch.setText("*required");
        }
        else{
            rsearch.setText("");
            try{
                if(rs.isBeforeFirst()==true){

                    while(rs.next()) {
                        String data[]={rs.getString("tname"),rs.getString("tid"),rs.getString("tphone"),rs.getString("t_load"),rs.getString("t_type")};

                        DefaultTableModel tbmodel=(DefaultTableModel)jTable1.getModel();
                        tbmodel.setRowCount(0);
                        tbmodel.addRow(data);
                    }
                }  else{
                    JOptionPane.showMessageDialog(null,"record not found","record not found",JOptionPane.ERROR_MESSAGE);
                }

            }
            catch(Exception e){
                System.out.println(e);

            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        DefaultTableModel tbmodel=(DefaultTableModel)jTable1.getModel();
        tbmodel.setRowCount(0);
        showrecord();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        dbclass dbclass=new dbclass();
        ResultSet rs = dbclass.sreachteacher(search.getText());
        if(search.getText().equals("Search here ...") || search.getText().equals("")){
            rsearch.setText("*required");
        }
        else{

            rsearch.setText("");
            try {
                if(rs.isBeforeFirst()==true){
                    
                     if(name.getText().equals("Enter Teacher Name") || name.getText().equals("") || id.getText().equals("Enter Teacher ID") || id.getText().equals("") || tload.getText().equals("Enter Teacher Load") || tload.getText().equals("") || phone.getText().equals("Enter Teacher Number") || phone.getText().equals(""))

        {
            if(name.getText().equals("Enter Teacher Name") || name.getText().equals("")){
                rname.setText("*required");
            }
            else{
                rname.setText("");
            }

            if(id.getText().equals("Enter Teacher ID") || id.getText().equals("")){
                rid.setText("*required");
            }
            else{
                rid.setText("");
            }
            if(tload.getText().equals("Enter Teacher Load") || tload.getText().equals("")){
                rload.setText("*required");
            }
            else{
                rload.setText("");
            }

            if(phone.getText().equals("Enter Teacher Number") || phone.getText().equals("")){
                rphone.setText("*required");
            }
            else{
                rphone.setText("");
            }

           
        }
        else{
                         
                         dbclass insert=new  dbclass();
             ResultSet rs0= insert.sreachteacher(search.getText());
             rs0.next();
             String chkName=rs0.getString("tname");
             String chkId=rs0.getString("tid");
             String chkNum=rs0.getString("tphone");
                         
             
             ResultSet rs1= insert.checkteacherName(name.getText());
             boolean chkTeacherName=rs1.isBeforeFirst(); 
             ResultSet rs2 = insert.sreachteacher(id.getText());
             boolean chkTeacherId=rs2.isBeforeFirst();
             ResultSet rs3 = insert.checkteacherNum(phone.getText());
             boolean chkTeacherNum=rs3.isBeforeFirst();
            
             
           
                         
            if((chkTeacherName==true && name.getText().equals(chkName)==false) || (chkTeacherId==true && id.getText().equals(chkId)==false) || (chkTeacherNum==true && phone.getText().equals(chkNum)==false)){
            
                if(chkTeacherName==true && name.getText().equals(chkName)==false)
                {
                JOptionPane.showMessageDialog(null,"dulicate entry This Name " +name.getText()+ " is Name of  Another Teacher Do little bit Changing in Name","dulicate entry",JOptionPane.WARNING_MESSAGE);
                }
                else if(chkTeacherId==true && id.getText().equals(chkId)==false)
                {
                JOptionPane.showMessageDialog(null,"dulicate entry "+id.getText()+ " is Already Found in Database ","dulicate entry",JOptionPane.WARNING_MESSAGE);
                }
                else if(chkTeacherNum==true && phone.getText().equals(chkNum)==false)
                {
                JOptionPane.showMessageDialog(null,"dulicate entry This Mobile Num "+phone.getText()+ " is Already in  use of Another Teacher ","dulicate entry",JOptionPane.WARNING_MESSAGE);
                }
            }
            else{
                         dbclass.updateteacher(name.getText(),id.getText(),phone.getText(),search.getText(),tload.getText(),ttype.getSelectedItem().toString());
                         JOptionPane.showMessageDialog(null,"teacher data succesfully updated","update teacher ",JOptionPane.INFORMATION_MESSAGE);
                         DefaultTableModel tbmodel=(DefaultTableModel)jTable1.getModel();
                         tbmodel.setRowCount(0);
                         showrecord();
                         name.setText("Enter Teacher Name");
                         name.setForeground(new Color(153,153,153));
                         rname.setText("");
                         id.setText("Enter Teacher ID");
                         id.setForeground(new Color(153,153,153));
                         rid.setText("");
                         tload.setText("Enter Teacher Load");
                         tload.setForeground(new Color(153,153,153));
                         rload.setText("");
                         phone.setText("Enter Teacher Number");
                         phone.setForeground(new Color(153,153,153));
                         rphone.setText("");
                         search.setText(null);
                     }
           
             
            }
                }  else{
                    JOptionPane.showMessageDialog(null,"record not found","record not found",JOptionPane.ERROR_MESSAGE);
                }   } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null,ex,String.valueOf(ex),JOptionPane.ERROR_MESSAGE);
                }
            }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int i= jTable1.getSelectedRow();
        TableModel model=jTable1.getModel();
        name.setText(model.getValueAt(i, 0).toString());
        name.setForeground(new Color(0,0,0));
        id.setText(model.getValueAt(i, 1).toString());
        search.setText(model.getValueAt(i, 1).toString());
        id.setForeground(new Color(0,0,0));
        phone.setText(model.getValueAt(i, 2).toString());
        phone.setForeground(new Color(0,0,0));
        tload.setText(model.getValueAt(i, 3).toString());
        tload.setForeground(new Color(0,0,0));
        ttype.setSelectedItem(model.getValueAt(i, 4));
       
                    rname.setText("");
                    rid.setText("");
                    rphone.setText("");
                    rsearch.setText("");
                    rload.setText("");
                    
    }//GEN-LAST:event_jTable1MouseClicked

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        rsearch.setText("");
        DefaultTableModel table = (DefaultTableModel)jTable1.getModel();
        String sch = search.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
        jTable1.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(sch));
    }//GEN-LAST:event_searchKeyReleased

    private void dptcombo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dptcombo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dptcombo2ActionPerformed

    private void tloadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tloadKeyReleased
        rload.setText("");
    }//GEN-LAST:event_tloadKeyReleased

    private void tloadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tloadFocusLost
        if(tload.getText().equals("")){
            tload.setText("Enter Teacher Load");
            tload.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_tloadFocusLost

    private void tloadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tloadFocusGained
        if(tload.getText().equals("Enter Teacher Load")){
            tload.setText("");
            tload.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_tloadFocusGained

    private void phoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneKeyReleased
        rphone.setText("");
    }//GEN-LAST:event_phoneKeyReleased

    private void phoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneFocusLost
        if(phone.getText().equals("")){
            phone.setText("Enter Teacher Number");
            phone.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_phoneFocusLost

    private void phoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneFocusGained
        if(phone.getText().equals("Enter Teacher Number")){
            phone.setText("");
            phone.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_phoneFocusGained

    private void idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyReleased
        rid.setText("");
    }//GEN-LAST:event_idKeyReleased

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void idFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idFocusLost
        if(id.getText().equals("")){
            id.setText("Enter Teacher ID");
            id.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_idFocusLost

    private void idFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idFocusGained
        if(id.getText().equals("Enter Teacher ID")){
            id.setText("");
            id.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_idFocusGained

    private void nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyReleased
        rname.setText("");
    }//GEN-LAST:event_nameKeyReleased

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed

    }//GEN-LAST:event_nameActionPerformed

    private void nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusLost
        if(name.getText().equals("")){
            name.setText("Enter Teacher Name");
            name.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_nameFocusLost

    private void nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusGained
        if(name.getText().equals("Enter Teacher Name")){
            name.setText("");
            name.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_nameFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    public javax.swing.JTable jTable1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phone;
    private javax.swing.JLabel rid;
    private javax.swing.JLabel rload;
    private javax.swing.JLabel rname;
    private javax.swing.JLabel rphone;
    private javax.swing.JLabel rsearch;
    public com.raven.swing.SearchText search;
    private javax.swing.JTextField tload;
    private javax.swing.JComboBox<String> ttype;
    // End of variables declaration//GEN-END:variables
}
